### PR TITLE
Add new welcome intro site

### PR DESCRIPTION
**Pull request by thinkh**
Closes Caleydo/tdp_bi_bioinfodb#647

Related PR: https://github.com/Caleydo/ordino_public/pull/10

First draft of the new welcome page. 

**Default state:**

ordino-welcome-page

**Hover over one step:**

ordino-welcome-page-hover

### CODE REVIEW

**Comment by thinkh** [comment]
Clue doesn't have a template.html. Do you mean like [this](https://github.com/phovea/phovea_clue/blob/develop/src/ACLUEWrapper.ts#L15-L36) instead?

**Comment by sgratzl** [comment]
> Clue doesn't have a template.html. Do you mean like this instead?

no more like the header template using
```
import * as template from 'html-loader!./_header.html';
```

I'm fine with inlining small template but this one is quite sophisticated. Actually html-loader should also take care regarding the image inclusion. So just use plain `src="..."`

**Comment by thinkh** [comment]
@mstreit Good idea! Here is how it looks:

image

**Comment by thinkh** [comment]
If you are fine with this version (and before merging) I have to extract the disclaimer to the ordino_public repo.

**Comment by mstreit** [comment]
Looks good! (maybe our BI colleagues have change request later on).

**Comment by thinkh** [comment]
Ok, then I will extract the disclaimer.

Should the start menu then be closed by default? Or should it be closed in the public version and open in the internal?

**Comment by thinkh** [comment]
The start menu will be closed for **ordino_public** instances, but remains open for **ordino** instances, due to faster access.

**Comment by lehnerchristian** [comment]
very nice, I like the new landing page, @thinkh 👍 

the only thing I saw is that in Firefox there is a scrollbar on the right and the logos on the bottom are cut off:
screenshot from 2018-01-05 14-08-45

**Comment by thinkh** [comment]
@lehnerchristian That highly depends on the viewport size. ;-) What are the viewport dimensions in your screenshot?

**Comment by lehnerchristian** [comment]
yes, I know 😉 
my viewport is 1908px wide and 942px high (the values are from `document.documentElement.clientWidth` and `document.documentElement.clientHeight`)

**Comment by thinkh** [comment]
Ok, I will have a look in Firefox. Btw. I noticed now that the header bar is also compressed in a strange way. I will see what I can do.

**Comment by mstreit** [comment]
@zichner, do you suggest any improvements for the intro site before it is merged?

**Comment by zichner** [comment]
Looks very nice!
One minor thing: I would likely put the disclaimer below the logos so that it looks less disruptive. What do you think?
And please add `:` behind `Disclaimer`

**Comment by mstreit** [comment]
Yes, I think putting the disclaimer at the very bottom is a good idea.

**Comment by thinkh** [comment]
Most recent version

image

**Comment by thinkh** [comment]
@lehnerchristian do you want to merge this PR or should I do it?

**Pull request merged**
