### PR TITLE
Add scrollbars to the start menu list components

### PR DESCRIPTION
**Pull request by oltionchampari**
Closes Caleydo/tdp_bi_bioinfodb#1292

### Summary
* Added a max height to the dataset and session lists and changed the overflow accordingly to get a scrollbar once the max height is reached
* We now overwrite the `position:relative`  of  the `.dropdown` bootstrap component and set it to initial  and use another parent element that does not have overflow hidden as relative
* The NamedSets have a bit more vertical spacing now in order for the active styles to show properly
* Added some extra padding to the SessionListItems

The scrolling functionality for the uploaded datasets card is included in  https://github.com/datavisyn/tdp_uploaded_data/pull/99

### Screenshot

scrollbars

### CODE REVIEW

**Review by thinkh — APPROVED** [review]
I changed how we add the padding to the container so that the focus glow is not cut truncated by the overflow of the container. Furthermore, I used bootstrap utility classes when possible.

In my tests it works fine now.

**Comment by thinkh** [comment]
@dvvanessastoiber could you also please test it one more time? You can simulate many elements by duplicating the list items in the dev tools. Thanks.

**Review by dvvanessastoiber — APPROVED** [review]
Works in my tests, thank you :+1:

**Comment by rumersdorfer** [comment]
Works fine.:+1:

**Pull request merged**
